### ISSUE TITLE
PAT permissons when using with private project 

### ISSUE THREAD

**Issue by futuredesignUK** [austenstone/project-add#45]
Great action!

Just to note when using this action to post issues to a **personal** namespace project board the PaT permissions need to have **repo** and **project** scopes (as well as admin:org) as the project target is not an org project.

The error message currently shows project not found:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/19208973/184308420-e5eb1f5a-3b6d-4a7a-a81f-fbd6fee06c9c.png">

**Comment by austenstone** [comment]
We added some information to the README. I also attempted to catch the error and throw it to user.
